<script setup async>
import {computed, onMounted, reactive, ref} from "vue";
import axios from "axios";
import {requestURl} from "@/utilities/request.js";
import {useRouter} from "vue-router";
import {clientStore} from "@/stores/clientStore.js";
import QRCode from "qrcode";

const props = defineProps([
	'totpToken'
])
const totpKey = ref("")
const formData = reactive({
	TOTP: ""
})

const loading = ref(false)
const replace = () => {
	formData.TOTP = formData.TOTP.replace(/\D/i, "")
}
const formFilled = computed(() => {
	return /^[0-9]{6}$/.test(formData.TOTP)
})

const store = clientStore()
const router = useRouter()

await axios.get(requestURl('/api/signin/totp'), {
	params: {
		Token: props.totpToken
	}
}).then(res => {
	let data = res.data
	if (data.status){
		if (data.message){
			totpKey.value = data.message
		}
	}else{
		store.newNotification(data.message, "danger")
		router.push('/signin')
	}
})

const emits = defineEmits(['clearToken'])

onMounted(() => {
	if (totpKey.value){
		QRCode.toCanvas(document.getElementById('qrcode'), totpKey.value, function (error) {})
	}
})

const verify = async (e) => {
	e.preventDefault()
	if (formFilled){
		loading.value = true
		await axios.post(requestURl('/api/signin/totp'), {
			Token: props.totpToken,
			UserProvidedTOTP: formData.TOTP
		}).then(res => {
			loading.value = false
			let data = res.data
			if (data.status){
				router.push('/')
			}else{
				store.newNotification(data.message, "danger")
			}
		}).catch(() => {
			store.newNotification("Sign in status is invalid", "danger")
			emits('clearToken')
		})
	}
}
</script>

<template>
<form class="d-flex flex-column gap-3" @submit="e => verify(e)">
	<div>
		<a role="button" @click="emits('clearToken')">
			<i class="me-2 bi bi-chevron-left"></i> Back
		</a>
	</div>
	<div class="">
		<h1 class="mb-3">Multi-Factor Authentication (MFA)</h1>
		<div class="card rounded-3" v-if="totpKey">
			<div class="card-body d-flex gap-3 flex-column">
				<h2 class="mb-0">Initial Setup</h2>
				<p class="mb-0">Please scan the following QR Code to generate TOTP with your choice of authenticator</p>
				<canvas id="qrcode" class="rounded-3 shadow "></canvas>
				<p class="mb-0">Or you can click the link below:</p>
				<div class="card rounded-3 ">
					<div class="card-body">
						<a :href="totpKey">
							{{ totpKey }}
						</a>
					</div>
				</div>
				<div class="alert alert-warning mb-0">
					<strong>
						Please note: You won't be able to see this QR Code again, so please save it somewhere safe in case you need to recover your TOTP key
					</strong>
				</div>
			</div>
		</div>
	</div>
	<hr v-if="totpKey">
	<div class="d-flex flex-column gap-3">
		<label for="totp">Enter the TOTP generated by your authenticator to verify</label>
		<input class="form-control form-control-lg rounded-3 text-center"
		       id="totp"
		       :disabled="loading"
		       autofocus
		       @keyup="replace()"
		       maxlength="6" type="text" inputmode="numeric"
		       placeholder="- - - - - -"
		       autocomplete="one-time-code" v-model="formData.TOTP">

		<button
			:disabled="!formFilled || loading"
			class="btn btn-primary rounded-3 btn-brand px-3 py-2">
			<Transition name="slide-right" mode="out-in">
				<span v-if="!loading" class="d-block">
					Continue <i class="ms-2 bi bi-arrow-right"></i>
				</span>
				<span v-else class="d-block">
					<i class="spinner-border spinner-border-sm"></i>
				</span>
			</Transition>
		</button>
	</div>

</form>
</template>

<style scoped>

</style>